[tool.poetry]
name = "cogito"
version = "0.1.0"
description = ""
authors = ["benballintyn <bbal@brandeis.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.1"
loguru = "^0.7.2"
optuna = "^4.1.0"
jsonlines = "^4.0.0"

[tool.poetry.group.dev.dependencies]
ipython = "^8.23.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
