name: Run Pytest

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full history to ensure branch checkout works
      
      - name: Ensure Correct Branch
        run: |
          git fetch origin ${{ github.head_ref }}:${{ github.head_ref }}
          git checkout ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root --with dev

      - name: Run Pytest
        run: |
          set -e
          set -x
          poetry run pytest --cov=cogito tests/ --cov-report=xml --cov-report=term > coverage.txt
        env:
          CI: true
      
      - name: Generate Coverage Badge
        id: generate_badge
        run: |
          COVERAGE=$(grep -Po '(?<=line-rate=\")\d+(\.\d+)?' coverage.xml | awk '{print int($1 * 100)}')
          echo "Coverage: $COVERAGE%"
          COLOR="red"
          if [ $COVERAGE -ge 90 ]; then
            COLOR="green"
          elif [ $COVERAGE -ge 75 ]; then
            COLOR="yellow"
          fi
          echo "<svg xmlns='http://www.w3.org/2000/svg' width='98' height='20'>
            <rect width='49' height='20' fill='#555'/>
            <rect x='49' width='49' height='20' fill='$COLOR'/>
            <text x='24.5' y='14' font-size='11' fill='#fff' text-anchor='middle'>coverage</text>
            <text x='73.5' y='14' font-size='11' fill='#fff' text-anchor='middle'>$COVERAGE%</text>
          </svg>" > coverage-badge.svg
      
      - name: Commit Coverage Badge
        if: matrix.python-version == '3.11'
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add coverage-badge.svg
          git commit -m "Update coverage badge: ${{ steps.generate_badge.outputs.coverage }}%"
          git push --set-upstream origin ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}